/*
 * Billing
 *
 * Keeps track of ordered items in the restaurant and offers a guest a possibility to pay their bills with different payment methods. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Api.Billing.Model
{
    /// <summary>
    /// Available payment method in the restaurant
    /// </summary>
    /// <value>Available payment method in the restaurant</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum PaymentMethod
    {
        /// <summary>
        /// Enum Cash for value: Cash
        /// </summary>
        [EnumMember(Value = "Cash")]
        Cash = 1,

        /// <summary>
        /// Enum DebitCard for value: DebitCard
        /// </summary>
        [EnumMember(Value = "DebitCard")]
        DebitCard = 2,

        /// <summary>
        /// Enum CreditCard for value: CreditCard
        /// </summary>
        [EnumMember(Value = "CreditCard")]
        CreditCard = 3

    }

}
